name: ci

on:
  push:
    branches:
      - "main"
env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: Hockey_Tickets_Check
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install qemu dependency
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository_owner }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          

        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          image: ${{ env.IMAGE_NAME }}
          context: .
          file: Dockerfile
          containerfiles: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/arm64
